title: BlockLearn Course Page Boilerplate
description: Create your own course page with live meeting feature in minutes
theme: jekyll-theme-cayman
google_analytics:
meeting_link: https://meet.jit.si/deneme-5d82b1302fa7d100066d0c88#jitsi_meet_external_api_id=0&amp;config.getroomnode=undefined&amp;interfaceConfig.SHOW_JITSI_WATERMARK=false&amp;interfaceConfig.SHOW_WATERMARK_FOR_GUESTS=false&amp;
course_activated: false
