title: BlockLearn Course Page Boilerplate
description: Create your own course page with live meeting feature in minutes
theme: jekyll-theme-cayman
google_analytics:
meeting_link: https://meet.jit.si/deneme-5d82b1302fa7d100066d0c88#jitsi_meet_external_api_id=0&amp;config.getroomnode=undefined&amp;interfaceConfig.SHOW_JITSI_WATERMARK=false&amp;interfaceConfig.SHOW_WATERMARK_FOR_GUESTS=false&amp;
meeting_link_before: <iframe  name="jitsiConferenceFrame0" id="jitsiConferenceFrame0" allowfullscreen="true" style="height: 100%; width: 100%; border: 0px;" allow="camera; microphone" src="
meeting_link_after: "></iframe>
